// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebApiProxy.Tasks.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class TsProxyTemplate : TsProxyTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"//------------------------------------------------------------------------------
//<auto-generated>
//  This file is auto-generated by WebApiProxy
//  Project site: http://github.com/faniereynders/webapiproxy
//  
//  Any changes to this file will be overwritten
//</auto-generated>
//------------------------------------------------------------------------------

module Api {
	//Models ");
            
            #line 16 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Metadata.Models.Count()));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 17 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 foreach(var model in this.Metadata.Models.ToList()) { 
            
            #line default
            #line hidden
            this.Write("\t\texport interface I");
            
            #line 18 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\t\t");
            
            #line 19 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 foreach (var param in model.Properties) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 20 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 20 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HandleType(param.Type)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 21 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t}\r\n\t");
            
            #line 23 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n\r\n\t\r\n\t//Namespaces ");
            
            #line 26 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Metadata.Definitions.Count()));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 27 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 foreach(var definition in this.Metadata.Definitions) { 
            
            #line default
            #line hidden
            this.Write("\t\tnamespace ");
            
            #line 28 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(definition.Name));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\t\t\r\n\r\n\t\t\t");
            
            #line 31 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 foreach(var method in definition.ActionMethods) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 32 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"

					
					var url = ("\"" + method.Url.Replace("{", "\" + ").Replace("}", " + \"") + "\"").Replace(" + \"\"","");
				
					var funcType = HandleType(method.ReturnType);
				
            
            #line default
            #line hidden
            this.Write("\t\t\t\texport async function ");
            
            #line 38 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name.ToCamelCasing()));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 38 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"

					var allParameters = method.UrlParameters.AsEnumerable();
					foreach(var param in allParameters) {
							var paramType = HandleType(param.Type);
						
            
            #line default
            #line hidden
            
            #line 42 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Name + (param.IsOptional ? "?" : "") + ": " + paramType));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t");
            
            #line 43 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 }  
            
            #line default
            #line hidden
            
            #line 43 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"

						if (method.BodyParameter != null) {
							var param = method.BodyParameter;
							var bodyType = HandleType(param.Type);
						
            
            #line default
            #line hidden
            
            #line 47 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Name + (param.IsOptional ? "?" : "") + ": " + bodyType));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 47 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
}
					
            
            #line default
            #line hidden
            this.Write(" options?: any): Promise<");
            
            #line 48 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(funcType));
            
            #line default
            #line hidden
            this.Write(">  {\r\n\t\t\t\t\tvar defaults = { fields: [] };\r\n\t\t\t\t\tvar settings = $.extend({}, defau" +
                    "lts, options || {});\r\n\t\t\t\t\tvar url = ");
            
            #line 51 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(url));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t\t\t\t\tif(settings.fields.length > 0) {\r\n\t\t\t\t\t\turl +=  url.indexOf(\"?\") == -1 " +
                    "? \"?\" : \"&\";\r\n\t\t\t\t\t\turl += \"fields=\" + settings.fields.join();\r\n\t\t\t\t\t}\r\n\r\n\r\n\t\t\t\t" +
                    "\t");
            
            #line 59 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 if (method.UrlParameters.Any()) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 60 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 foreach (var parameter in method.UrlParameters) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\turl = ApiLibrary.addDataToUrl(url, \"");
            
            #line 61 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write("\", <any> ");
            
            #line 61 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t\t");
            
            #line 62 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 63 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 65 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
if (method.Type.ToString().ToLower()=="get") {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\treturn await ApiLibrary.getCallAsync<");
            
            #line 66 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(funcType));
            
            #line default
            #line hidden
            this.Write(">(url,0);\r\n\t\t\t\t\t");
            
            #line 67 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 68 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
if (method.Type.ToString().ToLower()=="post") {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\treturn await ApiLibrary.postCallAsync<");
            
            #line 69 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(funcType));
            
            #line default
            #line hidden
            this.Write(">(url, 0, ");
            
            #line 69 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.BodyParameter.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t");
            
            #line 70 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 71 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
if (method.Type.ToString().ToLower()=="put") {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\treturn await ApiLibrary.putCallAsync<");
            
            #line 72 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(funcType));
            
            #line default
            #line hidden
            this.Write(">(url, 0, ");
            
            #line 72 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.BodyParameter.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t");
            
            #line 73 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t\t\t");
            
            #line 75 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t}\r\n\t");
            
            #line 77 "F:\External\WebApiProxy\WebApiProxy.Tasks\Templates\TsProxyTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class TsProxyTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
